from flask_restx import Namespace


AGENT_NS = Namespace("agent", description="Create and deploy various agent installations.")
ALERTS_NS = Namespace("alerts", description="Alerts related operations that allow operators to display or Acknowledge or Escalate alert events that come in.")
APP_NS = Namespace("app", description="Health page related operations.")
CATALOG_NS = Namespace("catalog", description="Catalog related operations used for installing HELM charts on the Kubernetes cluster.")
COLDLOG_NS = Namespace("coldlog", description="Cold log service operations.")
COMMON_NS = Namespace("common", path="/", description="Common related operations.")
CURATOR_NS = Namespace("curator", description="Elasticsearch curator.")
DEVICE_FACTS_NS = Namespace("facts", description="Device facts related operations.")
DIAGNOSTICS_NS = Namespace("diagnostics", description="Run diagnostics to help service desk troubleshoot tickets.",)
HEALTH_NS = Namespace("health", description="Health page related operations.")
HIVE_NS = Namespace("hive", description="Hive related webhook operations.")
JOB_NS = Namespace("jobs", description="Job Queue related operations.")
KUBERNETES_NS = Namespace("kubernetes", description="Kubernetes related operations.")
KIT_SETUP_NS = Namespace("kit", description="Kit setup related operations.")
KIT_TOKEN_NS = Namespace("kit-token", description="Kit tokens used for metrics.")
NOTIFICATIONS_NS = Namespace("notifications", description="Notifications for CVAH UI.")
POLICY_NS = Namespace("policy", description="Policy management related operations for Suricata and Zeek.")
PORTAL_NS = Namespace("portal", description="Portal related operations.")
SCALE_NS = Namespace("scale", description="Elastic scale related operations.")
SETINGS_NS = Namespace("settings", description="Kit setup related operations.")
TOOLS_NS = Namespace("tools", description="Tools page related operations.")
VERSION_NS = Namespace("version", description="Version related operations.")
