"""
Main module that controls the REST calls for the portal page.
"""
from app import (app, conn_mng, logger)
from app.common import OK_RESPONSE, ERROR_RESPONSE
from fabric.runners import Result
from flask import jsonify, Response
from shared.connection_mngs import FabricConnectionWrapper
from shared.constants import PORTAL_ID
from typing import List


DISCLUDES = ("elasticsearch.lan", "mysql.lan", "mumble-server.lan")


def _append_portal_link(portal_links: List, dns: str, ip: str = None):
    if dns == "grr-frontend.lan":
        if ip:            
            portal_links.append({'ip': 'https://' + ip, 'dns': 'https://' + dns, 'logins': 'admin/password'})
        else: 
            portal_links.append({'ip': '', 'dns': 'https://' + dns, 'logins': 'admin/password'})
    elif dns == "moloch-viewer.lan":
        if ip:
            portal_links.append({'ip': 'http://' + ip, 'dns': 'http://' + dns, 'logins': 'assessor/password'})
        else:
            portal_links.append({'ip': '', 'dns': 'http://' + dns, 'logins': 'assessor/password'})

    elif dns == "kubernetes-dashboard.lan":
        if ip:
            portal_links.append({'ip': 'https://' + ip, 'dns': 'https://' + dns, 'logins': ''})
        else:
            portal_links.append({'ip': '', 'dns': 'https://' + dns, 'logins': ''})
    else:
        if ip:
            portal_links.append({'ip': 'http://' + ip, 'dns': 'http://' + dns, 'logins': ''})
        else:
            portal_links.append({'ip': '', 'dns': 'http://' + dns, 'logins': ''})

def _isDiscluded(dns: str) -> bool:
    """
    Checks to see if the link should be discluded or included.

    :param dns: The dns name we are checking against the DISCLUDES list.
    :return:
    """
    for item in DISCLUDES:
        if dns == item:
            return True
    return False

@app.route('/api/get_portal_links', methods=['GET'])
def get_portal_links() -> Response:
    """
    Gets the portal links that were generated by the a fabric cron job.

    :return:
    """
    try:
        with FabricConnectionWrapper(conn_mng) as ssh_conn:
            portal_links = []
            ret_val = ssh_conn.run('cat /etc/dnsmasq_kube_hosts', hide=True)  # type: Result
            for line in ret_val.stdout.split('\n'):
                try:
                    ip, dns = line.split(' ')
                    if _isDiscluded(dns):
                        continue
                    _append_portal_link(portal_links, dns, ip)
                except ValueError as e:
                    pass
            return jsonify(portal_links)
    except Exception as e:
        return jsonify([])
    
    return ERROR_RESPONSE
