*** Variables ***
${locDITable}                       xpath=//cvah-docker-registry//mat-card
${locDITableTitle}                  xpath=//cvah-docker-registry//mat-card//mat-card-title
${locDITableColName1}               xpath=//cvah-docker-registry//mat-card//mat-card-content//table/thead/tr/th[1]
${locDITableColName2}               xpath=//cvah-docker-registry//mat-card//mat-card-content//table/thead/tr/th[2]
${locDITableColName3}               xpath=//cvah-docker-registry//mat-card//mat-card-content//table/thead/tr/th[3]
${locDITableColName4}               xpath=//cvah-docker-registry//mat-card//mat-card-content//table/thead/tr/th[4]
${locDITableRows}                   xpath=//cvah-docker-registry//mat-card-content//table/tbody/tr
