*** Variables ***
${locHelpDeskTitle}         xpath=//mat-grid-tile[1]//div/div[1]
${locHelpDeskHours}         xpath=//mat-grid-tile[1]//div/div[2]/p[1]
${locHelpDeskPhone}         xpath=//mat-grid-tile[1]//div/div[2]/p[2]
${locServiceNowTitle}       xpath=//mat-grid-tile[2]//div/div[1]
${locPmoSupportSiteTitle}   xpath=//mat-grid-tile[3]//div/div[1]
${locVersionInfoTitle}      xpath=//mat-grid-tile[4]//div/div[1]
