#!/usr/bin/env python3

import argparse
import re
from pathlib import Path


GLOBAL_KIT_ID_PATTERN = "^(((0[0-9][0-9]|1[0-2][0-7])(0[0-2][0-9]|0[0-3][0-2]))|((12[8-9]|1[3-9][0-9]|2[0-2][0-9]|23[012456789]|24[0-9]|25[0-3])(0[0-5][0-9]|06[0-4])))$"

def validate(global_kit_id: str) -> bool:
    if re.match(GLOBAL_KIT_ID_PATTERN, global_kit_id):
        return True
    else:
        return False

def write_switch_config(global_kit_id, folder):
    a, b = decode(global_kit_id)
    with open("Switch/switch.base.dell.conf", "r") as conf:
       configuration = conf.read()
    configuration = configuration.replace("10.101.32", f"10.{a}.{b}")
    configuration = configuration.replace("10.101.35", f"10.{a}.{b+1}")
    configuration = configuration.replace("SW-DIP-101", f"SW-DIP-{global_kit_id}")
    with open(folder + "/switch.conf", "w") as conf:
        conf.write(configuration)

def write_aux_switch_config(global_kit_id, folder):
    a, b = decode(global_kit_id)
    with open("Switch/auxiliary.switch.base.dell.conf", "r") as conf:
       configuration = conf.read()
    configuration = configuration.replace("10.101.32", f"10.{a}.{b}")
    configuration = configuration.replace("10.101.35", f"10.{a}.{b+1}")
    configuration = configuration.replace("SW-AUX-101", f"SW-AUX-{global_kit_id}")
    with open(folder + "/aux.conf", "w") as conf:
        conf.write(configuration)

def write_firewall_config(global_kit_id, domain, folder):
    a, b = decode(global_kit_id)
    with open("Firewall/firewall.base.xml", "r") as conf:
       configuration = conf.read()
    configuration = configuration.replace("10.101.32", f"10.{a}.{b}")
    configuration = configuration.replace("10.101.33", f"10.{a}.{b+3}")
    configuration = configuration.replace("10.101.35", f"10.{a}.{b+1}")
    configuration = configuration.replace("10.101.37", f"10.{a}.{b+2}")
    configuration = configuration.replace(".lan", ".{}".format(domain))
    configuration = configuration.replace("<domain>lan</domain>", f"<domain>{domain}</domain>")
    with open(folder + "/firewall.xml", "w") as conf:
        conf.write(configuration)

def decode(global_kit_id: str):
    if not validate(global_kit_id):
       raise ValueError("Invalid global kit id.")

    a = int(global_kit_id[:3])
    b = int(global_kit_id[3:])

    if a <= 127:
        x = a
        y = b * 4 + 124
    else:
        x = a
        y = (b - 1) * 4

    return (x, y)


def main():
    parser = argparse.ArgumentParser()
    parser.add_argument("--global-kit-id", type=str)
    parser.add_argument("--domain", type=str)
    parser.add_argument("--config", action="append")
    args = parser.parse_args()
    try:
        folder = f"Kit_{args.global_kit_id}_{args.domain}"
        Path(folder).mkdir(parents=False, exist_ok=True)
        if "switch" in args.config:
            write_switch_config(args.global_kit_id, folder)
        if "aux-switch" in args.config:
            write_aux_switch_config(args.global_kit_id, folder)
        if "firewall" in args.config:
            write_firewall_config(args.global_kit_id, args.domain, folder)
    except ValueError as e:
        print(str(e))

if __name__ == "__main__":
    main()
